### ISSUE TITLE
Fix resource linking through bookingsync_portal config

### ISSUE THREAD

**Issue by Fredar** [BookingSync/bookingsync_portal#23]
Probably setting `resource_klass_name` is not working as expected

**Comment by Mandaryn** [comment]
what was wrong with this one, still and issue?

**Comment by Fredar** [comment]
I had to define this module locally in holidaylettings https://github.com/BookingSync/bsa-holidaylettings/pull/30/files#diff-bde90505e6863ce9e2a3abd9ec596cc6R1 and remove the link to portal  as it wasnt working properly.

**Comment by Mandaryn** [comment]
imho this whole json-api thing should be completely removed from this gem until someone really starts working on the ember ui, it's some premature overengineering at this point

**Comment by Fredar** [comment]
makes sense, feel free to close the ticket then

**Comment by Mandaryn** [comment]
json api already removed

**Comment by Mandaryn** [comment]
fixed by https://github.com/BookingSync/bookingsync_portal/issues/38
